version: "2"

checks:
  method-lines:
    config:
      threshold: 50

checkstyle:
  enabled: true
  checks:
    com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
      enabled: false

plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "11"
      minimum_severity: minor
    checks:
      squid:S2885:
        enabled: false

exclude_patterns:
  - "**/jooq/"
  - "**/test/"