version: "2"

checkstyle:
  enabled: true
  checks:
    com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
      enabled: false

plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "11"

exclude_patterns:
  - "**/jooq/"
  - "**/jooq/generated/"