version: "2"

checks:
  method-lines:
    config:
      threshold: 50

checkstyle:
  enabled: true
  checks:
    com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
      enabled: false


plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "11"
    checks:
      squid:S2885:
        enabled: false
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false