version: "2"

checkstyle:
  enabled: true
  checks:
    com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
      enabled: false
    method-lines:
      config:
        threshold: 50

plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "11"
      minimum_severity: critical
    checks:
      squid:S2885:
        enabled: false

exclude_patterns:
  - "**/jooq/"
  - "**/test/"