language: java
jdk:
  - oraclejdk11

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - sudo mysql -e "use mysql; update user set password=PASSWORD('rootroot') where User='root';FLUSH PRIVILEGES;"
  - sudo service mysql restart


cache:
  directories:
    - $HOME/.m2

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)