language: java
jdk:
  - oraclejdk11

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_install:
  - sudo mysql_upgrade -u root -prootroot


cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)