language: java
jdk:
  - oraclejdk11

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_install:
  - mysql -u root --password="rootroot" < test/travis.sql


cache:
  directories:
    - $HOME/.m2

sudo: false

script: mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)