language: java

jdk:
  - oraclejdk11

sudo: false

services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE movieStore;'

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - pavlenko.av92@gmail.com
    on_success: never
    on_failure: never

env:
  global:
    - CODECOV_TOKEN="d583518b-95d1-415e-a777-ec6a4ecab96b"