language: java
jdk:
  - oraclejdk11

services:
  - mysql

before_install:
  - mysql -u root --password='rootroot'

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)