language: java
dist: xenial
jdk:
  - openjdk11

sudo: false

services:
  - mysql

before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('rootroot') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

before_install:
  - mysql -u root -e 'CREATE DATABASE movieStore;'


cache:
  directories:
    - $HOME/.m2

script:
  - mvn test

after_script:
#  JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter
#  \format-coverage target/site/jacoco-aggregate/jacoco.xml
#  \--input-type jacoco
#  ./cc-test-reporter upload-coverage
  - ./cc-test-reporter format-coverage -d -t jacoco target/site/jacoco-aggregate/jacoco.xml
  - ./cc-test-reporter upload-coverage -d

notifications:
  email:
    recipients:
      - pavlenko.av92@gmail.com
    on_success: never
    on_failure: never

env:
  global:
    - CC_TEST_REPORTER_ID=c4f8dceccb951ebd666457ab7c33e05cff78995fa5557d5d4945f1c8a2cb685d