language: java
jdk:
  - oraclejdk11

services:
  - mysql

before_install:
  - sudo mysql -e "use mysql; update user set password=PASSWORD('rootroot') where User='root';FLUSH PRIVILEGES;"
  - sudo service mysql restart

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)