language: java
jdk:
  - oraclejdk11

sudo: false

#services:
#  - mysql
#
#addons:
#  apt:
#    sources:
#      - mysql-5.7-trusty
#    packages:
#      - mysql-server

#before_install:
#  - mysql -e 'CREATE DATABASE myapp_test;'
#  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

cache:
  directories:
    - $HOME/.m2



after_success:
  - bash <(curl -s https://codecov.io/bash)