codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - "/home/garret/snap/ideaprojects/movie-store/dao/src/main/java/com/garret/movies/dao/**/*"
    - "/home/garret/snap/ideaprojects/movie-store/omdb-client/api/src/main/java/com/garret/movies/omdb/api/**/*"
    - "/home/garret/snap/ideaprojects/movie-store/omdb-client/impl/src/main/java/com/garret/movies/omdb/impl/config/.*"