version: '2'

services:
  db:
    image: mysql:5.7.14
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: movieStore
      MYSQL_USER: root
      MYSQL_PASSWORD: rootroot
